repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.900
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: local
    hooks:
      - id: ruff
        name: Run Ruff
        entry: ruff run
        language: system
        types: [python]
