version: "3.9"

services:
  backend:
    image: {{ cookiecutter.project_name }}
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    container_name: {{ cookiecutter.project_name }}_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - database
      - mailhog
    networks:
      - backend-net
    stdin_open: true
    tty: true

  database:
    image: postgres:14-alpine
    container_name: {{ cookiecutter.project_name }}_database
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend-net

  cache:
    image: redis:7.0-alpine
    container_name: {{ cookiecutter.project_name }}_cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass password

  mailhog:
    image: mailhog/mailhog
    container_name: {{ cookiecutter.project_name }}_mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

networks:
  backend-net:
    driver: bridge

volumes:
  postgres_data:
